### ISSUE TITLE
Add Tip Uses Rinkeby Contract and 0 Gas

### ISSUE THREAD

**Issue by mikeghen** [tellor-io/tellorPriceView#18]
This is the transaction I get in metamask when I click add tip:
![Screen Shot 2020-07-01 at 12 23 28 AM](https://user-images.githubusercontent.com/5077880/86202754-29f5fd00-bb31-11ea-8463-416ff0c721fd.png)
Note the contract address is the Rinkeby Tellor address. There is also default to no gas, which can be fixed with Metamask easily. I think it should default to use standard gas prices automatically.

**Comment by maciejczypek** [comment]
One question. I've done the gas fee and contract addresses (mainnet and Rinkeby) fixes + I don't have "Sent Ether" label but "Contract interaction" label instead. The only thing I'm not sure about is this 0 ETH ($0.00) amount on the top. So, if I have gas fee 0.2 ETH and 0 amount, the Total displays 0.2 ETH. I'm not sure if that's wrong because the method addTip is not payable, so we don't pass value argument to the send() but we pass tip amount the addTip method itself earlier - so I'm wondering if that's intended or it's the part of the bug (displaying 0 ETH on the top)?
